# Generated by Django 5.2.17 on 2026-08-05 08:22

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('first_name', models.CharField(max_length=60, verbose_name='first name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('role', models.CharField(choices=[('shipper', 'Shipper'), ('transporter', 'Transporter')], max_length=20, verbose_name='role')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='ar', max_length=5, verbose_name='preferred language')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShipperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='company name')),
                ('commercial_registration', models.CharField(blank=True, max_length=30, verbose_name='commercial registration number')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='national ID / Iqama')),
                ('license_number', models.CharField(blank=True, max_length=30, verbose_name='driving licence number')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='base city')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, verbose_name='years of experience')),
                ('is_online', models.BooleanField(default=False, verbose_name='available for work')),
                ('last_online_at', models.DateTimeField(blank=True, null=True, verbose_name='last went online')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating')),
                ('completed_trips', models.PositiveIntegerField(default=0, verbose_name='completed trips')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='accounts_em_user_id_fc82dd_idx')],
            },
        ),
    ]
