# Generated by Django 5.2.17 on 2026-08-05 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('standard', 'Standard (dry van)'), ('refrigerated', 'Refrigerated'), ('flatbed', 'Flatbed'), ('lowbed', 'Lowbed'), ('tanker', 'Tanker'), ('container', 'Container carrier'), ('curtain_side', 'Curtain side'), ('tipper', 'Tipper / dump'), ('car_carrier', 'Car carrier'), ('livestock', 'Livestock')], max_length=20, verbose_name='body type')),
                ('size', models.CharField(choices=[('small', 'Small (up to 3 tons)'), ('medium', 'Medium (3 to 10 tons)'), ('large', 'Large (10 to 25 tons)'), ('heavy', 'Heavy trailer (25+ tons)')], max_length=10, verbose_name='size class')),
                ('make', models.CharField(max_length=60, verbose_name='make')),
                ('model_name', models.CharField(max_length=60, verbose_name='model')),
                ('manufacture_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='year')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='plate number')),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='payload capacity (tons)')),
                ('capacity_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='load volume (m³)')),
                ('bed_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='bed length (m)')),
                ('has_tail_lift', models.BooleanField(default=False, verbose_name='tail lift')),
                ('has_gps_tracking', models.BooleanField(default=False, verbose_name='GPS tracking')),
                ('min_temperature_c', models.SmallIntegerField(blank=True, help_text='Refrigerated vehicles only.', null=True, verbose_name='minimum temperature (°C)')),
                ('max_temperature_c', models.SmallIntegerField(blank=True, null=True, verbose_name='maximum temperature (°C)')),
                ('base_city', models.CharField(max_length=80, verbose_name='base city')),
                ('operating_regions', models.CharField(blank=True, help_text='Comma separated list of cities or regions served.', max_length=255, verbose_name='operating regions')),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='indicative price per km (SAR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='listed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'transporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['body_type', 'size'], name='vehicles_ve_body_ty_bbbbf4_idx'), models.Index(fields=['base_city'], name='vehicles_ve_base_ci_9e7c19_idx')],
            },
        ),
    ]
