# Generated by Django 5.2.17 on 2026-08-05 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('general', 'General goods'), ('foodstuff', 'Foodstuff'), ('perishable', 'Perishable / chilled'), ('construction', 'Construction materials'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('livestock', 'Livestock'), ('hazardous', 'Hazardous materials'), ('vehicles', 'Vehicles')], default='general', max_length=20, verbose_name='cargo type')),
                ('cargo_description', models.TextField(max_length=1000, verbose_name='cargo description')),
                ('weight_tons', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='weight (tons)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='volume (m³)')),
                ('required_body_type', models.CharField(blank=True, choices=[('standard', 'Standard (dry van)'), ('refrigerated', 'Refrigerated'), ('flatbed', 'Flatbed'), ('lowbed', 'Lowbed'), ('tanker', 'Tanker'), ('container', 'Container carrier'), ('curtain_side', 'Curtain side'), ('tipper', 'Tipper / dump'), ('car_carrier', 'Car carrier'), ('livestock', 'Livestock')], max_length=20, verbose_name='required body type')),
                ('pickup_city', models.CharField(max_length=80, verbose_name='pickup city')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='pickup address')),
                ('dropoff_city', models.CharField(max_length=80, verbose_name='drop-off city')),
                ('dropoff_address', models.CharField(max_length=255, verbose_name='drop-off address')),
                ('pickup_date', models.DateField(verbose_name='preferred pickup date')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='offered price (SAR)')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12, verbose_name='status')),
                ('decline_reason', models.CharField(blank=True, max_length=255, verbose_name='decline reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('shipper', models.ForeignKey(limit_choices_to={'role': 'shipper'}, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_requests', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(limit_choices_to={'role': 'transporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_requests', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'shipment request',
                'verbose_name_plural': 'shipment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12, verbose_name='status')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='agreed price (SAR)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='shipments.shipmentrequest')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipmentrequest',
            index=models.Index(fields=['transporter', 'status'], name='shipments_s_transpo_0b7266_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentrequest',
            index=models.Index(fields=['shipper', 'status'], name='shipments_s_shipper_ef73ba_idx'),
        ),
    ]
